### ISSUE TITLE
Tobias Meixner suggestions

### ISSUE THREAD

**Issue by shtefcs** [vanila-io/mention-ghost-theme#1]
Dear Stefan,

thanks for the offer.
Though I am not interested. I think I will give your theme a few more release cycles to consider again.

I will be happy to promote is once its mature or has a new great feature.
For me for example you are missing alt-attributes on author images, tags are not linked in post list, author names are not linked, footer colors look mixed up, few images are missing in your demo blog, disqus container missing padding and please consider using gulp+scss to make it more flexible for user.

Thank you.

**Comment by jelenajjo** [comment]
These are fixed:
- [x] Missing alt-attributes on author images
- [x] Tags should be linked
- [x] Author should be linked
- [x] Disqus container missing padding

About the missing images in my demo, it has to do with my blog, there is no issue in theme.
