### ISSUE TITLE
Code blocks are not formatted

### ISSUE THREAD

**Issue by dmeents** [vanila-io/mention-ghost-theme#10]
Hello! 

Love the theme guys, just having an issue at the moment with code blocks which don't seem to be working at all. I've indicated them with the proper markdown in the editor, but on the published page they are not formatted at all, please see the screenshot below. 

Let me know if I can help, thanks for the support!

![theme bug](https://cloud.githubusercontent.com/assets/16874322/16207315/1349821a-36f2-11e6-9b08-d48e1c333bbd.png)

**Comment by dmeents** [comment]
Easy solution for now, you can add this with the code injection feature into the header of your ghost blog:

```
<!-- http://highlightjs.readthedocs.org/en/latest/css-classes-reference.html -->  
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.5/styles/agate.min.css">  
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.5/highlight.min.js"></script>  
<script>hljs.initHighlightingOnLoad();</script>  
<style>  
  pre {
    word-wrap: normal;
    -moz-hyphens: none;
    -ms-hyphens: none;
    -webkit-hyphens: none;
    hyphens: none;
    font-size: 1em;
    line-height: 1.75em;
    margin: 3em 0em;
  }
    pre code, pre tt {
    white-space: pre;
  }

  code { 
    background: rgba(219, 227, 227, 0.35);
    padding: 0.25em 1em; 
    margin: 0.1em 0.15em;
    border: 1px solid #CFD6D6;
    display: inline-block;
  }
</style>  
```

**Comment by shtefcs** [comment]
Tnx for submitting this issue @dmeents . @jelenajjo will check it out.

**Comment by jelenajjo** [comment]
@dmeents Hi, thanks for participating ^^ I just fixed this issue, you can check :)
