### ISSUE TITLE
Free up whitespace on header?

### ISSUE THREAD

**Issue by 7MinSec** [vanila-io/mention-ghost-theme#4]
Hi there,

I downloaded your theme and love it - just had a style question for you (and if I should email this or go through another channel please tell me).  Could I free up some of the space in the blog title to tighten things up a bit?  See my crude drawing here:

https://dl.dropboxusercontent.com/u/5473387/ZZZ-bjheader.jpg

Brian

**Comment by shtefcs** [comment]
hi Brian. yes you probably can do it easy. let's ask @jelenajjo how to do it.

**Comment by jelenajjo** [comment]
Hello @braimee . I'm glad you like theme. :) Here is how you can remove extra space:
1. Go to `/assets/css/custom.min.css` file
2. Find this part of code: 
`.heading{display:table;padding:21px;width:100%;height:300px;background:#f8f8f8}`
3. Replace it with this: 
 `.heading{display:table;padding:21px;width:100%;height:auto;margin-top:30px;background:#f8f8f8}`
4. Save it and you should be good now. :)

Let me know if you still need help! :)

**Comment by 7MinSec** [comment]
Thank you @jelenajjo I'll give that a shot soon. 

On a side note, I have a handful of other minor questions about the theme that probably have easy fixes.  Is creating separate github question/issues the best way to raise those?  I don't want to clutter up this area if it's something that's more easily handled via email or another form of communications.

**Comment by jelenajjo** [comment]
Yes, you could make another issue. Because someone else might be interested in same so it can help. :)

**Comment by 7MinSec** [comment]
Ok the .css to get the header smaller worked perfect - thanks again!

Now I'll go open up some new issues for other little tweaks I'm hopeful you can help me with :-)
