### ISSUE TITLE
Make the first paragraph of each post "regular" font?

### ISSUE THREAD

**Issue by 7MinSec** [vanila-io/mention-ghost-theme#6]
Hi,

It looks like the first line/paragraph of each page or post is bold w/italics.  Can that be disabled?

Thanks,
Brian

**Comment by jelenajjo** [comment]
Just go to `/assets/css/custom.css` file and remove [this](https://github.com/vanila-io/mention-ghost-theme/blob/master/assets/css/custom.css#L443-L444) lines of code:
