### ISSUE TITLE
Have posts include clickable tags?

### ISSUE THREAD

**Issue by 7MinSec** [vanila-io/mention-ghost-theme#8]
Hi,

When I look at my list of posts, from the home page, they have a title, the author, the publish date, and then the tag associated with that post.  

Could I make a style change so that the associated tag could be clickable and link to all posts with associated tag?  See this:

https://dl.dropboxusercontent.com/u/5473387/bj-tags.jpg

Brian

**Comment by jelenajjo** [comment]
@braimee  Fixed. :+1:

**Comment by 7MinSec** [comment]
Hey thanks!  Sorry for the probably obvious question, but which file contains this change?

**Comment by jelenajjo** [comment]
Here inside [loop.hbs](https://github.com/vanila-io/mention-ghost-theme/blob/master/partials/loop.hbs#L20) file. :)
